
[[_installation]]
= Installation

First of all you need to add the dependency to your build file.

.Gradle Installation
[source,subs='verbatim,attributes']
----
repositories {
    mavenCentral()
}

dependencies {
    implementation "com.agorapulse:micronaut-log4aws:{project-version}"
}
----

TIP: There are variants for older Micronaut versions as well. You can use `micronaut-1.0` or `micronaut-2.0` suffix for
 different versions of Micronaut.

Also be sure that your build file **does not contain any referrence to Logback**:

.Build File Cleanup
[source,subs='verbatim,attributes']
----
dependencies {
    // remove following line from your build file if present
    runtime "ch.qos.logback:logback-classic:1.2.3"
}
----

Then remove Logback configuration file from `src/main/resources/logback.groovy`
and replace it with a new file `log4j2.xml` with following content. Feel free to update the file to fit your needs.


.Log4J2 Configuration
[source,xml,subs='verbatim,attributes']
----
include::../../../../../subprojects/micronaut-log4aws/src/test/resources/log4j2.xml[lines=1;21..51]
----

TIP: The library can configure `Sentry` appender for you if you forget to specify it in the configuration file.

As a last step you need to create a file `sentry.properties` for sentry configuration - also in `src/main/resources`:

.sentry.properties
[source,properties,subs='verbatim,attributes']
----
# guarantees all events are logged before the function execution is finished
async=false

# you should consider adding your packages here to enable filtering of stack traces in Sentry

# stacktrace.app.packages=agorapulse,com.agorapulse
----
