
[[_usage]]
= Usage

== Sentry Integration

Sentry logger is initialised automatically at application startup. A `SentryClient` bean is available for injection to access the lower-level API.

Sentry events are enriched with the following information if available:

* `aws_region`
* `aws_default_region`
* `lambda_function_name`
* `lambda_function_version`
* `lambda_handler`
* `lambda_execution_environment`
* `lambda_log_group_name`
* `lambda_log_stream_name`
* `lambda_memory_size`
* `req.path`
* `req.method`
* `req.remoteHost`
* `req.serverHost`
* `req.parameters`
* `req.headers`

== Ensure Exception Being Logged with @LogError

All the errors have to be logged to be propagated to Sentry. You can use `LogErrors` around advice
with your entry-point method to simplify the logging boilerplate:

.Using LogError Annotation
[source,java]
----
/**
* This class is an entrypoint called by AWS Lambda. Keep the code to minimum.
* Method handleRequest is called directly by the AWS Lambda container.
*/
class ReportsExporter extends FunctionInitializer implements RequestHandler<SQSEvent, Void> {

    @Inject private ReportsService reportsService;

    Void handleRequest(SQSEvent event, Context context) {
        return reportsService.handlerRequest(event);
    }

}

/**
* This class is handled by Micronaut and can use the advice.
*/
@Singleton
class ReportsService implements RequestHandler<SQSEvent, Void> {

    @LogError
    Void handleRequest(SQSEvent event, Context context) {
        return reportsService.handlerRequest(event);
    }

}
----

WARNING: The annotation applied to the function class itself has no effect as the function class is executed by AWS Lambda container.
