/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2020-2025 Agorapulse.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'org.kordamp.gradle.groovy-project'          version kordampPluginVersion
        id 'org.kordamp.gradle.checkstyle'              version kordampPluginVersion
        id 'org.kordamp.gradle.codenarc'                version kordampPluginVersion
        id 'org.kordamp.gradle.guide'                   version kordampPluginVersion
        id 'org.kordamp.gradle.coveralls'               version kordampPluginVersion
        id 'com.github.kt3k.coveralls'                  version coverallsPluginVersion
        id 'org.ajoberstar.git-publish'                 version gitPublishPluginVersion
        id 'io.github.gradle-nexus.publish-plugin'      version nexusPluginVersion
    }
}

buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath group: 'io.micronaut.gradle', name: 'micronaut-minimal-plugin', version: micronautGradlePluginVersion
    }
}

plugins {
    id 'com.gradle.develocity' version '4.0.2'
}

develocity {
    buildScan {
        publishing.onlyIf { true }
        termsOfUseUrl = 'https://gradle.com/terms-of-service'
        termsOfUseAgree = 'yes'
    }
}

rootProject.name = 'micronaut-log4aws-root'

['subprojects', 'docs', 'examples', 'testprojects'].each { dir ->
    file(dir).eachDir { sub ->
        include sub.name
        project(":${sub.name}").projectDir = sub
        def explicitBuildFile = new File(sub, "${sub.name}.gradle")
        if (explicitBuildFile.exists()) {
            project(":${sub.name}").buildFileName = "${sub.name}.gradle"
        }
    }
}
